eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: SchedualServiceHi-feign

feign:
   hystrix:
     enabled: true
